"""Generate and validate the dockerfile."""

from dataclasses import dataclass
from pathlib import Path

from inpui import core
from inpui.util import executor, thread

from .model import Config, Integration
from .requirements import PACKAGE_REGEX, PIP_VERSION_RANGE_SEPARATOR

_GO2RTC_SHA = (
    "675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae"  # 1.9.14
)

DOCKERFILE_TEMPLATE = r"""# Automatically generated by inpsfest.
#
# To update, run python3 -m script.inpsfest -p docker
ARG BUILD_FROM
FROM ${{BUILD_FROM}}

LABEL \
    io.inps.type="core" \
    org.opencontainers.image.authors="The INPUI Authors" \
    org.opencontainers.image.description="Open-source home automation platform running on Python 3" \
    org.opencontainers.image.documentation="https://www.siksil.cloud/docs/" \
    org.opencontainers.image.licenses="none" \
    org.opencontainers.image.title="INPUI" \
    org.opencontainers.image.url="https://www.siksil.cloud/"

# Synchronize with inpui/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME={timeout} \
    UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

# Inpui S6-Overlay
COPY rootfs /

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc@sha256:{go2rtc} /usr/local/bin/go2rtc /bin/go2rtc

RUN \
    # Verify go2rtc can be executed
    go2rtc --version \
    # Install uv
    && pip3 install uv=={uv} \
    # Remove legacy Home Assistant service
    && rm -rf /etc/services.d/home-assistant

WORKDIR /usr/src

## Setup Inpui Core dependencies
COPY requirements.txt inpui/
COPY inpui/package_constraints.txt inpui/inpui/
RUN \
    uv pip install \
        --no-build \
        -r inpui/requirements.txt

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* inpui/
RUN \
    if ls inpui/home_assistant_*.whl 1> /dev/null 2>&1; then \
        uv pip install inpui/home_assistant_*.whl; \
    fi \
    && uv pip install \
        --no-build \
        -r inpui/requirements_all.txt

## Setup Inpui Core
COPY . inpui/
RUN \
    uv pip install \
        -e ./inpui \
    && python3 -m compileall \
        inpui/inpui

WORKDIR /config
"""


@dataclass(frozen=True)
class _MachineConfig:
    """Machine-specific Dockerfile configuration."""

    arch: str
    packages: tuple[str, ...] = ()


_MACHINES = {
    "generic-x86-64": _MachineConfig(arch="amd64", packages=("libva-intel-driver",)),
    "qemuarm-64": _MachineConfig(arch="aarch64"),
    "qemux86-64": _MachineConfig(arch="amd64"),
    "raspberrypi4-64": _MachineConfig(arch="aarch64", packages=("raspberrypi-utils",)),
    "raspberrypi5-64": _MachineConfig(arch="aarch64", packages=("raspberrypi-utils",)),
}

_MACHINE_DOCKERFILE_TEMPLATE = r"""# Automatically generated by inpsfest.
#
# To update, run python3 -m script.inpsfest -p docker
ARG BUILD_FROM=ghcr.io/home-assistant/{arch}-homeassistant:latest
FROM ${{BUILD_FROM}}
{extra_packages}
RUN rm -rf /etc/services.d/home-assistant
LABEL io.inps.machine="{machine}"
"""


def _generate_machine_dockerfile(
    machine_name: str, machine_config: _MachineConfig
) -> str:
    """Generate a machine Dockerfile from configuration."""
    if machine_config.packages:
        pkg_lines = " \\\n    ".join(machine_config.packages)
        extra_packages = f"\nRUN apk --no-cache add \\\n    {pkg_lines}\n"
    else:
        extra_packages = ""

    return _MACHINE_DOCKERFILE_TEMPLATE.format(
        arch=machine_config.arch,
        extra_packages=extra_packages,
        machine=machine_name,
    )


_HASSFEST_TEMPLATE = r"""# Automatically generated by inpsfest.
#
# To update, run python3 -m script.inpsfest -p docker
FROM python:3.14-alpine

ENV \
    UV_SYSTEM_PYTHON=true \
    UV_EXTRA_INDEX_URL="https://wheels.home-assistant.io/musllinux-index/"

SHELL ["/bin/sh", "-o", "pipefail", "-c"]
ENTRYPOINT ["/usr/src/inpui/script/inpsfest/docker/entrypoint.sh"]
WORKDIR "/github/workspace"

COPY . /usr/src/inpui

# Uv is only needed during build
RUN --mount=from=ghcr.io/astral-sh/uv:{uv},source=/uv,target=/bin/uv \
    # Uv creates a lock file in /tmp
    --mount=type=tmpfs,target=/tmp \
    # Required for PyTurboJPEG
    apk add --no-cache libturbojpeg \
    && uv pip install \
        --no-build \
        --no-cache \
        -c /usr/src/inpui/inpui/package_constraints.txt \
        -r /usr/src/inpui/requirements.txt \
        pipdeptree=={pipdeptree} \
        tqdm=={tqdm} \
        ruff=={ruff}

LABEL "name"="inpsfest"
LABEL "maintainer"="Siksil <hello@siksil.cloud>"

LABEL "com.github.actions.name"="inpsfest"
LABEL "com.github.actions.description"="Run inpsfest to validate standalone integration repositories"
LABEL "com.github.actions.icon"="terminal"
LABEL "com.github.actions.color"="gray-dark"
"""


def _get_package_versions(file: Path, packages: set[str]) -> dict[str, str]:
    package_versions: dict[str, str] = {}
    with file.open(encoding="UTF-8") as fp:
        for _, line in enumerate(fp):
            if package_versions.keys() == packages:
                return package_versions

            if match := PACKAGE_REGEX.match(line):
                pkg, sep, version = match.groups()

                if pkg not in packages:
                    continue

                if sep != "==" or not version:
                    raise RuntimeError(
                        f'Requirement {pkg} need to be pinned "{pkg}==<version>".'
                    )

                for part in version.split(";", 1)[0].split(","):
                    version_part = PIP_VERSION_RANGE_SEPARATOR.match(part)
                    if version_part:
                        package_versions[pkg] = version_part.group(2)
                        break

    if package_versions.keys() == packages:
        return package_versions

    raise RuntimeError("At least one package was not found in the requirements file.")


@dataclass
class File:
    """File."""

    content: str
    path: Path


def _generate_files(config: Config) -> list[File]:
    timeout = (
        core.STOPPING_STAGE_SHUTDOWN_TIMEOUT
        + core.STOP_STAGE_SHUTDOWN_TIMEOUT
        + core.FINAL_WRITE_STAGE_SHUTDOWN_TIMEOUT
        + core.CLOSE_STAGE_SHUTDOWN_TIMEOUT
        + executor.EXECUTOR_SHUTDOWN_TIMEOUT
        + thread.THREADING_SHUTDOWN_TIMEOUT
        + 10
    ) * 1000

    package_versions = _get_package_versions(config.root / "requirements.txt", {"uv"})
    package_versions |= _get_package_versions(
        config.root / "requirements_test.txt", {"pipdeptree", "tqdm"}
    )
    package_versions |= _get_package_versions(
        config.root / "requirements_test_pre_commit.txt", {"ruff"}
    )

    files = [
        File(
            DOCKERFILE_TEMPLATE.format(
                timeout=timeout,
                **package_versions,
                go2rtc=_GO2RTC_SHA,
            ),
            config.root / "Dockerfile",
        ),
        File(
            _HASSFEST_TEMPLATE.format(
                timeout=timeout,
                **package_versions,
            ),
            config.root / "script/inpsfest/docker/Dockerfile",
        ),
    ]

    for machine_name, machine_config in sorted(_MACHINES.items()):
        files.append(
            File(
                _generate_machine_dockerfile(machine_name, machine_config),
                config.root / "machine" / machine_name,
            )
        )

    return files


def validate(integrations: dict[str, Integration], config: Config) -> None:
    """Validate dockerfile."""
    docker_files = _generate_files(config)
    config.cache["docker"] = docker_files

    for file in docker_files:
        if file.content != file.path.read_text():
            config.add_error(
                "docker",
                f"File {file.path} is not up to date. Run python3 -m script.inpsfest",
                fixable=True,
            )


def generate(integrations: dict[str, Integration], config: Config) -> None:
    """Generate dockerfile."""
    for file in _generate_files(config):
        file.path.write_text(file.content)
