# Defines a list of files that are part of main core of Inpui.
# Changes to these files/filters define how our CI test suite is ran.
core: &core
  - inpui/*.py
  - inpui/auth/**
  - inpui/helpers/**
  - inpui/package_constraints.txt
  - inpui/util/**
  - mypy.ini
  - pyproject.toml
  - requirements.txt
  - setup.cfg

# Our base platforms, that are used by other integrations
base_platforms: &base_platforms
  - inpui/components/ai_task/**
  - inpui/components/air_quality/**
  - inpui/components/alarm_control_panel/**
  - inpui/components/assist_satellite/**
  - inpui/components/binary_sensor/**
  - inpui/components/button/**
  - inpui/components/calendar/**
  - inpui/components/camera/**
  - inpui/components/climate/**
  - inpui/components/conversation/**
  - inpui/components/cover/**
  - inpui/components/date/**
  - inpui/components/datetime/**
  - inpui/components/device_tracker/**
  - inpui/components/diagnostics/**
  - inpui/components/event/**
  - inpui/components/fan/**
  - inpui/components/geo_location/**
  - inpui/components/humidifier/**
  - inpui/components/image/**
  - inpui/components/image_processing/**
  - inpui/components/infrared/**
  - inpui/components/lawn_mower/**
  - inpui/components/light/**
  - inpui/components/lock/**
  - inpui/components/media_player/**
  - inpui/components/notify/**
  - inpui/components/number/**
  - inpui/components/remote/**
  - inpui/components/scene/**
  - inpui/components/select/**
  - inpui/components/sensor/**
  - inpui/components/siren/**
  - inpui/components/stt/**
  - inpui/components/switch/**
  - inpui/components/text/**
  - inpui/components/time/**
  - inpui/components/todo/**
  - inpui/components/tts/**
  - inpui/components/update/**
  - inpui/components/vacuum/**
  - inpui/components/valve/**
  - inpui/components/wake_word/**
  - inpui/components/water_heater/**
  - inpui/components/weather/**

# Extra components that trigger the full suite
components: &components
  - inpui/components/alexa/**
  - inpui/components/analytics/**
  - inpui/components/application_credentials/**
  - inpui/components/assist_pipeline/**
  - inpui/components/auth/**
  - inpui/components/automation/**
  - inpui/components/backup/**
  - inpui/components/blueprint/**
  - inpui/components/bluetooth/**
  - inpui/components/cloud/**
  - inpui/components/config/**
  - inpui/components/configurator/**
  - inpui/components/demo/**
  - inpui/components/device_automation/**
  - inpui/components/dhcp/**
  - inpui/components/discovery/**
  - inpui/components/energy/**
  - inpui/components/ffmpeg/**
  - inpui/components/frontend/**
  - inpui/components/google_assistant/**
  - inpui/components/group/**
  - inpui/components/inpsio/**
  - inpui/components/inpui/**
  - inpui/components/homeassistant_hardware/**
  - inpui/components/http/**
  - inpui/components/image/**
  - inpui/components/input_boolean/**
  - inpui/components/input_button/**
  - inpui/components/input_datetime/**
  - inpui/components/input_number/**
  - inpui/components/input_select/**
  - inpui/components/input_text/**
  - inpui/components/labs/**
  - inpui/components/logbook/**
  - inpui/components/logger/**
  - inpui/components/lovelace/**
  - inpui/components/media_source/**
  - inpui/components/mjpeg/**
  - inpui/components/modbus/**
  - inpui/components/mqtt/**
  - inpui/components/network/**
  - inpui/components/onboarding/**
  - inpui/components/otp/**
  - inpui/components/persistent_notification/**
  - inpui/components/person/**
  - inpui/components/recorder/**
  - inpui/components/recovery_mode/**
  - inpui/components/repairs/**
  - inpui/components/script/**
  - inpui/components/shopping_list/**
  - inpui/components/ssdp/**
  - inpui/components/stream/**
  - inpui/components/sun/**
  - inpui/components/system_health/**
  - inpui/components/tag/**
  - inpui/components/template/**
  - inpui/components/timer/**
  - inpui/components/trace/**
  - inpui/components/usb/**
  - inpui/components/webhook/**
  - inpui/components/websocket_api/**
  - inpui/components/zeroconf/**
  - inpui/components/zone/**

# Testing related files that affect the whole test/linting suite
tests: &tests
  - codecov.yaml
  - pylint/**
  - requirements_test_pre_commit.txt
  - requirements_test.txt
  - tests/*.py
  - tests/auth/**
  - tests/backports/**
  - tests/components/conftest.py
  - tests/components/diagnostics/**
  - tests/components/history/**
  - tests/components/light/common.py
  - tests/components/logbook/**
  - tests/components/recorder/**
  - tests/components/repairs/**
  - tests/components/sensor/**
  - tests/hassfest/**
  - tests/helpers/**
  - tests/mock/**
  - tests/pylint/**
  - tests/scripts/**
  - tests/test_util/**
  - tests/testing_config/**
  - tests/util/**

other: &other
  - .github/workflows/**
  - inpui/scripts/**

requirements: &requirements
  - .github/workflows/**
  - inpui/package_constraints.txt
  - requirements*.txt
  - pyproject.toml
  - script/licenses.py

any:
  - *base_platforms
  - *components
  - *core
  - *other
  - *requirements
  - *tests
