# Automatically generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
ARG BUILD_FROM
FROM ${BUILD_FROM}

LABEL \
    io.inps.type="core" \
    org.opencontainers.image.authors="The INPUI Authors" \
    org.opencontainers.image.description="Open-source home automation platform running on Python 3" \
    org.opencontainers.image.documentation="https://www.siksil.cloud/docs/" \
    org.opencontainers.image.licenses="none" \
    org.opencontainers.image.title="INPUI" \
    org.opencontainers.image.url="https://www.siksil.cloud/"

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

# Inpui S6-Overlay
COPY rootfs /

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae /usr/local/bin/go2rtc /bin/go2rtc

RUN \
    # Verify go2rtc can be executed
    go2rtc --version \
    # Install uv
    && pip3 install uv==0.11.6

WORKDIR /usr/src

## Setup Inpui Core dependencies
COPY requirements.txt inpui/
COPY inpui/package_constraints.txt inpui/inpui/
RUN \
    uv pip install \
    --no-build \
    -r inpui/requirements.txt

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* inpui/
RUN \
    if ls inpui/home_assistant_*.whl 1> /dev/null 2>&1; then \
    uv pip install inpui/home_assistant_*.whl; \
    fi \
    && uv pip install \
    --no-build \
    -r inpui/requirements_all.txt

## Setup Inpui Core
COPY . inpui/
RUN \
    uv pip install \
    -e ./inpui \
    && python3 -m compileall \
    inpui/inpui

WORKDIR /config
