# Automatically generated by inpsfest.
#
# To update, run python3 -m script.inpsfest -p docker
ARG BUILD_FROM=ghcr.io/home-assistant/amd64-homeassistant-base:latest
FROM ${BUILD_FROM}

LABEL \
    io.inps.type="core" \
    org.opencontainers.image.authors="The INPUI Authors" \
    org.opencontainers.image.description="Open-source home automation platform running on Python 3" \
    org.opencontainers.image.documentation="https://www.siksil.cloud/docs/" \
    org.opencontainers.image.licenses="none" \
    org.opencontainers.image.title="INPUI" \
    org.opencontainers.image.url="https://www.siksil.cloud/"

# Synchronize with inpui/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

# Inpui S6-Overlay
COPY rootfs /

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae /usr/local/bin/go2rtc /bin/go2rtc

# Add cloudflared binary
COPY --from=cloudflare/cloudflared:latest /usr/local/bin/cloudflared /bin/cloudflared

RUN \
    # Verify go2rtc can be executed
    go2rtc --version \
    # Verify cloudflared can be executed
    && cloudflared --version \
    # Install uv
    && pip3 install uv==0.11.6 \
    # Remove legacy Home Assistant service
    && rm -rf /etc/services.d/home-assistant

WORKDIR /usr/src

## Setup Inpui Core dependencies
COPY requirements.txt inpui/
COPY inpui/package_constraints.txt inpui/inpui/
RUN \
    uv pip install \
        --no-build \
        -r inpui/requirements.txt

COPY requirements_all.txt inpui/
# Mandatory frontend wheel
COPY home_assistant_frontend-*.whl inpui/
# Optional intents wheel
COPY requirements_all.txt home_assistant_intents-* inpui/
RUN \
    uv pip install inpui/home_assistant_frontend-*.whl \
    && if ls inpui/home_assistant_intents-*.whl 1> /dev/null 2>&1; then \
        uv pip install inpui/home_assistant_intents-*.whl; \
    fi \
    && uv pip install \
        --no-build \
        -r inpui/requirements_all.txt

## Setup Inpui Core
COPY . inpui/
RUN \
    uv pip install \
        -e ./inpui \
    && python3 -m compileall \
        inpui/inpui

WORKDIR /config
